name 'demo-repo-customresource'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo-repo-customresource'
long_description 'Installs/Configures demo-repo-customresource'
version '0.1.0'
